# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.
services:
  postgres:
    image: postgres:15 # Você pode escolher a versão desejada
    container_name: motocycle_postgres
    environment:
      POSTGRES_USER: admin # Nome de usuário do PostgreSQL
      POSTGRES_PASSWORD: 2846Cycle # Senha do usuário
      POSTGRES_DB: motocycle_db # Nome do banco de dados a ser criado
    ports:
      - "5432:5432" # Mapeia a porta 5432 do container para a máquina host
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistência dos dados
  localstack:
    image: localstack/localstack
    container_name: motocycle_localstack
    ports:
      - "4566:4566" # Porta padrão para a API do LocalStack
      - "4571:4571" # Portas para serviços específicos (opcional)
    environment:
      - SERVICES=sqs,sns,s3 # Serviços que você quer habilitara
      - EDGE_PORT=4566
      - AWS_DEFAULT_REGION=us-east-1
      - CORS_ALLOW_ALL_ORIGINS=1 # Permitir todas as origens
      - USE_SINGLE_REGION=1
      - DEBUG=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Necessário para permitir que LocalStack crie contêineres
volumes:
  postgres_data:
